@startuml screenTransition
title 画面遷移図 (クライアント)
hide empty description

state タイトル画面 : ユーザ名入力欄
state タイトル画面 : サーバIPアドレス入力欄
state 待機画面 : コメント

state ライブ画面 : ステージ
state ライブ画面 : コメント
state ライブ画面 {
	state エール一覧 : 消費エメトストーン数
	state エール一覧 {
		state エール確認画面 : エールのモデル
		state エール確認画面 : 消費エメトストーン数
		state エール確認画面
	}
}

[*] -r-> タイトル画面
ライブ画面 -u-> タイトル画面 : 退出する/\nライブ終了
タイトル画面 --> 待機画面 : 参加する
待機画面 --> ライブ画面 : ライブ開始

@enduml