@startuml presenter
left to right direction

actor プレゼンタ as presenter

rectangle プレゼンタ端末 {
	presenter --> (移動する)
	presenter --> (コメントを見る)
	presenter --> (エールを見る)
	presenter --> (オブジェクトを持ち上げる)
}

@enduml