@startuml 1_joinLive

component サーバ as server
component コンソール as console
component コントローラ as controller
component クライアント as client

server <-l- client : 接続要求
server <-r- controller : 接続要求
server <-d- console : ライブ開始命令\nライブ終了命令

@enduml